[package]
name = "pop-telemetry"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
reqwest.workspace = true
serde_json.workspace = true
hostname.workspace = true
log.workspace = true