name: Test `pop install` on Ubuntu

on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t pop-install-ubuntu -f Dockerfile.ubuntu .

    - name: Run Docker container
      id: docker_run
      run: |
        docker run -d pop-install-ubuntu
        sleep 5  # Wait for 5 seconds
        echo "::set-output name=container_id::$(docker ps -q)"

    - name: Download and extract pop binary
      run: |
        docker exec ${{ steps.docker_run.outputs.container_id }} wget https://github.com/r0gue-io/pop-cli/releases/download/0.1.0-alpha.1/pop-x86_64-unknown-linux-gnu.tar.gz
        docker exec ${{ steps.docker_run.outputs.container_id }} tar -xzf pop-x86_64-unknown-linux-gnu.tar.gz -C /usr/local/bin/
        docker exec ${{ steps.docker_run.outputs.container_id }} chmod +x /usr/local/bin/pop

    - name: Verify pop binary
      run: |
        docker exec ${{ steps.docker_run.outputs.container_id }} ls -l /usr/local/bin/pop

    - name: Execute pop-cli binary
      run: docker exec ${{ steps.docker_run.outputs.container_id }} /usr/local/bin/pop --help