name: Test pop install

on:
  push:
    branches: [ "alexd10s/pop-install" ]
  pull_request:
    branches: [ "alexd10s/pop-install" ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_ACTOR: pop-cli

jobs:
  build:

    runs-on: ${{ matrix.platform.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        platform:
          # Linux
          - os: ubuntu-22.04
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          # macOS
          - os: macos-14
            target: aarch64-apple-darwin
          - os: macos-14
            target: x86_64-apple-darwin

    steps:
    - name: Free up space on runner
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - uses: actions/checkout@v3
    - name: Build default features
      run: cargo build

    - name: Run cargo run install
      run: cargo run install -y